[package]
name = "universe-cli"
version = "0.1.0"
edition = "2021"
description = "A CLI tool for managing NixOS configurations"

[dependencies]
clap = { version = "4.3.19", features = ["derive"] }
colored = "2.0.0"
which = "4.4.0"
edit = "0.1.4"
